version: "3.9"

services:
  # Customer Service + Database
  postgres-clientes:
    image: postgres:16-alpine
    container_name: postgres-clientes
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: clientes_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_clientes_data:/var/lib/postgresql/data
    networks:
      - plataforma-network

  customer-service:
    build:
      context: ./customer-service
      dockerfile: Dockerfile
    container_name: customer-service
    restart: unless-stopped
    depends_on:
      - postgres-clientes
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-clientes:5432/clientes_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "123"
      SERVER_PORT: 8081
    ports:
      - "8081:8081"
    networks:
      - plataforma-network

  # Product Service + Database

  postgres-produtos:
    image: postgres:16-alpine
    container_name: postgres-produtos
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: produtos_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_produtos_data:/var/lib/postgresql/data
    networks:
      - plataforma-network

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    container_name: product-service
    restart: unless-stopped
    depends_on:
      - postgres-produtos
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-produtos:5432/produtos_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "123"
      SERVER_PORT: 8082
    ports:
      - "8082:8082"
    networks:
      - plataforma-network

  # Currency Service + Database
  postgres-cotacoes:
    image: postgres:16-alpine
    container_name: postgres-cotacoes
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: cotacoes_db
    ports:
      - "5435:5432"
    volumes:
      - postgres_cotacoes_data:/var/lib/postgresql/data
    networks:
      - plataforma-network

  currency-service:
    build:
      context: ./currency-service
      dockerfile: Dockerfile
    container_name: currency-service
    restart: unless-stopped
    depends_on:
      - postgres-cotacoes
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-cotacoes:5432/cotacoes_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "123"
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - plataforma-network

volumes:
  postgres_clientes_data:
  postgres_produtos_data:
  postgres_cotacoes_data:

networks:
  plataforma-network:
    driver: bridge
