version: "3.9"

services:
  # Customer Service + Database
  postgres-customer:
    image: postgres:16-alpine
    container_name: postgres-customer
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: customer_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_customer_data:/var/lib/postgresql/data
    networks:
      - plataforma-network

  customer-service:
    build:
      context: ./customer-service
      dockerfile: Dockerfile
    container_name: customer-service
    restart: unless-stopped
    depends_on:
      - postgres-customer
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-customer:5432/customer_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "123"
      SERVER_PORT: 8081
    ports:
      - "8081:8081"
    networks:
      - plataforma-network

  # Product Service + Database

  postgres-product:
    image: postgres:16-alpine
    container_name: postgres-product
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: product_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_product_data:/var/lib/postgresql/data
    networks:
      - plataforma-network

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    container_name: product-service
    restart: unless-stopped
    depends_on:
      - postgres-product
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-product:5432/product_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "123"
      SERVER_PORT: 8082
    ports:
      - "8082:8082"
    networks:
      - plataforma-network

  # Currency Service + Database
  postgres-cotacoes:
    image: postgres:16-alpine
    container_name: postgres-currency
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: currency_db
    ports:
      - "5435:5432"
    volumes:
      - postgres_currency_data:/var/lib/postgresql/data
    networks:
      - plataforma-network

  currency-service:
    build:
      context: ./currency-service
      dockerfile: Dockerfile
    container_name: currency-service
    restart: unless-stopped
    depends_on:
      - postgres-currency
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-currency:5432/currency_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "123"
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - plataforma-network

volumes:
  postgres_customer_data:
  postgres_product_data:
  postgres_currency_data:

networks:
  plataforma-network:
    driver: bridge
