CREATE TABLE usuarios
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    surname    VARCHAR(255)                            NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    usuario_login VARCHAR(255)                         NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    role       VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    active     BOOLEAN,
    CONSTRAINT pk_usuarios PRIMARY KEY (id)
);