version: "3.9"

services:
  postgres-cotacoes:
    image: postgres:16-alpine
    container_name: postgres-cotacoes
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: cotacoes_db
    ports:
      - "5435:5432"
    volumes:
      - postgres_clientes_data:/var/lib/postgresql/data

volumes:
  postgres_cotacoes_data: