version: "3.9"

services:
  postgres-clientes:
    image: postgres:16-alpine
    container_name: postgres-produtos
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: produtos_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_clientes_data:/var/lib/postgresql/data

volumes:
  postgres_clientes_data: